name: infobits_intl
description: Internationalization data for countries, languages, currencies, and continents
version: 1.0.0
homepage: https://github.com/infobits-io/infobits-intl
repository: https://github.com/infobits-io/infobits-intl

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.0
  html: ^0.15.4
